
type songType = "Single" | "Track" | "Remix" | "RadioEdit" | "A Cappella";
type albumType = "EP" | "B-Side" | "Remix" | "Studio" | "Deluxe" | "Series" | "";

interface SongInfo extends Array<SongInfo> {
    id: number,
    ISRC: string,
    label: string[] | string,
    artist: string,
    feature?: string[] | string,
    track_title: string,
    track_subTitle?: string,
    track_album: string,
    track_subAlbum?: string,

    track_mp3Url: string,
    track_coverUrl: string,

    genres: string | string[],
    track_type: songType | songType[],
    album_type?: songType | songType[],
    track_number: number,
    played: number,

    year: number,
    release_date: Date,
    explicit: boolean,
    languages: "EDIT",

    writers: string | string[],
    producers: string | string[],
    engineers: string | string[],
    other_assistants: string | string[],

    key: string,
    duration: number,
    bpm: number,
    popularity: number,
    energy: number,
    danceability: number,
    valence: number,
    acousticness: number,
    instrumentalness: number,
    liveness: number,
    speechiness: number,
    loudness: number,
}



const myDearMelancholy_EP = [
    {
        "id": "21",
        "ISRC": "USUG11800560",
        "label": ["Universal Music Group", "Republic Records", "XO Records"],
        "artist": "The Weeknd",
        "feature": "",
        "track_title": "Call Out My Name",
        "track_subTitle": "",
        "track_album": "My Dear Melancholy,",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/myDearMelancholy/callOutMyName_song1.mp3",
        "track_coverUrl": "../material/albums/myDearMelancholy/myDearMelancholy_albumCover.jfif",

        "genres": ["R&B", "Soul", "Pop", "Dark Pop", "Alternative R&B"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "1",
        "played": "0",

        "year": "2018",
        "release_date": "03/30/2018",
        "explicit": "No",
        "languages": "English",

        "writers": ["Frank Dukes", "Nicolas Jaar", "The Weeknd"],
        "producers": "Frank Dukes",
        "engineers": ["Shin Kamiyama", "Jaycen Joshua", "MaddMix", "David Nakaji"],
        "other_assistants": "",

        "key": "C# major",
        "duration": "3:48",
        "bpm": "134",
        "popularity": "83",
        "energy": "59",
        "danceability": "46",
        "valence": "18",
        "acousticness": "17",
        "instrumentalness": "0",
        "liveness": "31",
        "speechiness": "4",
        "loudness": "-5",
    },

    {
        "id": "22",
        "ISRC": "USUG11800562",
        "label": ["Universal Music Group", "Republic Records", "XO Records"],
        "artist": "The Weeknd",
        "feature": "",
        "track_title": "Try Me",
        "track_subTitle": "",
        "track_album": "My Dear Melancholy,",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/myDearMelancholy/tryMe_song2.mp3",
        "track_coverUrl": "../material/albums/myDearMelancholy/myDearMelancholy_albumCover.jfif",

        "genres": ["R&B", "Soul", "Pop", "Electropop", "Alternative R&B"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "2",
        "played": "0",

        "year": "2018",
        "release_date": "03/30/2018",
        "explicit": "No",
        "languages": "English",

        "writers": ["Marz", "Belly", "Mike WiLL Made-It", "Frank Dukes", "DaHeala", "The Weeknd"],
        "producers": ["DaHeala", "Marz", "Frank Dukes", "Mike WiLL Made-It"],
        "engineers": ["Shin Kamiyama", "Jaycen Joshua", "MaddMix", "David Nakaji"],
        "other_assistants": "",

        "key": "Ab minor",
        "duration": "3:41",
        "bpm": "92",
        "popularity": "73",
        "energy": "68",
        "danceability": "46",
        "valence": "11",
        "acousticness": "60",
        "instrumentalness": "0",
        "liveness": "13",
        "speechiness": "6",
        "loudness": "-6",
    },

    {
        "id": "23",
        "ISRC": "USUG11800564",
        "label": ["Universal Music Group", "Republic Records", "XO Records"],
        "artist": "The Weeknd",
        "feature": "",
        "track_title": "Wasted Times",
        "track_subTitle": "",
        "track_album": "My Dear Melancholy,",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/myDearMelancholy/wastedTimes_song3.mp3",
        "track_coverUrl": "../material/albums/myDearMelancholy/myDearMelancholy_albumCover.jfif",

        "genres": ["R&B", "Soul", "Pop", "Electropop", "Alternative R&B"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "3",
        "played": "0",

        "year": "2018",
        "release_date": "03/20/2018",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["Skrillex", "Frank Dukes", "Starrah", "The Weeknd"],
        "producers": ["Frank Dukes", "Skrillex"],
        "engineers": ["Shin Kamiyama", "Jaycen Joshua", "MaddMix", "David Nakaji"],
        "other_assistants": "",

        "key": "Bb minor",
        "duration": "3:40",
        "bpm": "123",
        "popularity": "72",
        "energy": "68",
        "danceability": "56",
        "valence": "29",
        "acousticness": "61",
        "instrumentalness": "0",
        "liveness": "11",
        "speechiness": "6",
        "loudness": "-6",
    },

    {
        "id": "24",
        "ISRC": "USUG11800570",
        "label": ["Universal Music Group", "Republic Records", "XO Records"],
        "artist": "The Weeknd",
        "feature": "Gesaffelstein",
        "track_title": "I Was Never There",
        "track_subTitle": "",
        "track_album": "My Dear Melancholy,",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/myDearMelancholy/IWasNeverThere_song4.mp3",
        "track_coverUrl": "../material/albums/myDearMelancholy/myDearMelancholy_albumCover.jfif",

        "genres": ["R&B", "Soul", "Electropop", "Alternative R&B"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "4",
        "played": "0",

        "year": "2018",
        "release_date": "03/20/2018",
        "explicit": "No",
        "languages": "English",

        "writers": ["Frank Dukes", "Gesaffelstein", "The Weeknd"],
        "producers": ["Frank Dukes", "Gesaffelstein"],
        "engineers": ["Shin Kamiyama", "Jaycen Joshua", "MaddMix", "David Nakaji"],
        "other_assistants": "",

        "key": "Bb major",
        "duration": "4:01",
        "bpm": "113",
        "popularity": "69",
        "energy": "74",
        "danceability": "32",
        "valence": "16",
        "acousticness": "14",
        "instrumentalness": "0",
        "liveness": "16",
        "speechiness": "3",
        "loudness": "-4",
    },

    {
        "id": "25",
        "ISRC": "USUG11800566",
        "label": ["Universal Music Group", "Republic Records", "XO Records"],
        "artist": "The Weeknd",
        "feature": "Gesaffelstein",
        "track_title": "Hurt You",
        "track_subTitle": "",
        "track_album": "My Dear Melancholy,",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/myDearMelancholy/hurtYou_song5.mp3",
        "track_coverUrl": "../material/albums/myDearMelancholy/myDearMelancholy_albumCover.jfif",

        "genres": ["R&B", "Soul", "Electropop", "Alternative R&B"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "5",
        "played": "0",

        "year": "2018",
        "release_date": "03/20/2018",
        "explicit": "No",
        "languages": "English",

        "writers": ["Guy-Manuel de Homem-Christo", "Cirkut", "Frank Dukes", "Gesaffelstein", "The Weeknd"],
        "producers": ["Cirkut", "Guy-Manuel de Homem-Christo", "Gesaffelstein"],
        "engineers": ["Shin Kamiyama", "Florian Lagatta", "Jaycen Joshua"],
        "other_assistants": "",

        "key": "F minor",
        "duration": "3:50",
        "bpm": "92",
        "popularity": "71",
        "energy": "72",
        "danceability": "48",
        "valence": "36",
        "acousticness": "26",
        "instrumentalness": "0",
        "liveness": "11",
        "speechiness": "15",
        "loudness": "-7",
    },

    {
        "id": "26",
        "ISRC": "USUG11800568",
        "label": ["Universal Music Group", "Republic Records", "XO Records"],
        "artist": "The Weeknd",
        "feature": "",
        "track_title": "Privilege",
        "track_subTitle": "",
        "track_album": "My Dear Melancholy,",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/myDearMelancholy/privilege_song6.mp3",
        "track_coverUrl": "../material/albums/myDearMelancholy/myDearMelancholy_albumCover.jfif",

        "genres": ["R&B", "Soul", "Alternative R&B"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "6",
        "played": "0",

        "year": "2018",
        "release_date": "03/20/2018",
        "explicit": "No",
        "languages": "English",

        "writers": ["Doc McKinney", "Ben Billions", "Brennan Savage", "The Weeknd", "DaHeala", "Frank Dukes"],
        "producers": ["DaHeala", "Frank Dukes"],
        "engineers": ["Shin Kamiyama", "Jaycen Joshua", "MaddMix", "David Nakaji"],
        "other_assistants": "",

        "key": "B minor",
        "duration": "2:51",
        "bpm": "94",
        "popularity": "70",
        "energy": "56",
        "danceability": "40",
        "valence": "37",
        "acousticness": "92",
        "instrumentalness": "0",
        "liveness": "13",
        "speechiness": "3",
        "loudness": "-7",
    },

    {
        "id": "27",
        "ISRC": "USUG11901347",
        "label": ["Universal Music Group", "Republic Records", "XO Records"],
        "artist": "The Weeknd",
        "feature": "",
        "track_title": "Call Out My Name",
        "track_subTitle": "A Capella",
        "track_album": "My Dear Melancholy,",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/myDearMelancholy/callOutMyNameACappella_song7.mp3",
        "track_coverUrl": "../material/albums/myDearMelancholy/myDearMelancholy_albumCover.jfif",

        "genres": ["A Cappella", "R&B", "Soul", "Alternative R&B"],
        "track_type": ["Track", "A Cappella"],
        "album_type": "EP",
        "track_number": "7",
        "played": "0",

        "year": "2019",
        "release_date": "05/10/2019",
        "explicit": "No",
        "languages": "English",

        "writers": "The Weeknd",
        "producers": "Frank Dukes",
        "engineers": "",
        "other_assistants": "",

        "key": "C# major",
        "duration": "3:45",
        "bpm": "135",
        "popularity": "58",
        "energy": "34",
        "danceability": "40",
        "valence": "46",
        "acousticness": "89",
        "instrumentalness": "0",
        "liveness": "31",
        "speechiness": "4",
        "loudness": "-7",
    },

]









const seven_EP = [

    {
        "id": "28",
        "ISRC": "USSM11902498",
        "label": "Columbia Records",
        "artist": "Lil Nas X",
        "feature": "Billy Ray Cyrus",
        "track_title": "Old Town Road",
        "track_subTitle": "(Remix)",
        "track_album": "7",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/seven/oldTownRoadRemix_song1.mp3",
        "track_coverUrl": "../material/albums/seven/seven_albumCover.jfif",

        "genres": ["Rap", "Country Rap", "Country", "Pop Country", "Trap"],
        "track_type": ["Track", "Remix"],
        "album_type": "EP",
        "track_number": "1",
        "played": "0",

        "year": "2019",
        "release_date": "04/05/2019",
        "explicit": "No",
        "languages": "English",

        "writers": ["Jozzy", "Atticus Ross", "Trent Reznor", "Billy Ray Cyrus", "Lil Nas X"],
        "producers": ["Trent Reznor", "Atticus Ross", "YoungKio"],
        "engineers": ["Eric Lagg", "Joe Grasso"],
        "other_assistants": "",

        "key": "F# major",
        "duration": "2:37",
        "bpm": "136",
        "popularity": "83",
        "energy": "62",
        "danceability": "88",
        "valence": "64",
        "acousticness": "5",
        "instrumentalness": "0",
        "liveness": "11",
        "speechiness": "10",
        "loudness": "-6",
    },

    {
        "id": "29",
        "ISRC": "USSM11903948",
        "label": "Columbia Records",
        "artist": "Lil Nas X",
        "feature": "",
        "track_title": "Panini",
        "track_subTitle": "",
        "track_album": "7",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/seven/panini_song2.mp3",
        "track_coverUrl": "../material/albums/seven/seven_albumCover.jfif",

        "genres": ["Pop", "Rap", "Dance Pop", "Alternative Rap"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "2",
        "played": "0",

        "year": "2019",
        "release_date": "06/20/2019",
        "explicit": "No",
        "languages": "English",

        "writers": ["Dot Da Genius", "David Biral", "Denzel Baptiste", "Lil Nas X"],
        "producers": ["Dot Da Genius", "Take a Daytrip"],
        "engineers": ["Colin Leonard", "DJ Swivel", "Denzel Baptiste", "Thomas Cullison"],
        "other_assistants": "",

        "key": "F minor",
        "duration": "1:55",
        "bpm": "154",
        "popularity": "69",
        "energy": "59",
        "danceability": "70",
        "valence": "48",
        "acousticness": "34",
        "instrumentalness": "0",
        "liveness": "12",
        "speechiness": "8",
        "loudness": "-6",
    },

    {
        "id": "30",
        "ISRC": "USSM11903949",
        "label": "Columbia Records",
        "artist": "Lil Nas X",
        "feature": "Travis Barker",
        "track_title": "F9mily",
        "track_subTitle": "(You & Me)",
        "track_album": "7",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/seven/f9mily\(You&Me\)_song3.mp3",
        "track_coverUrl": "../material/albums/seven/seven_albumCover.jfif",

        "genres": ["Pop", "Rock", "Dance Pop", "Pop rock"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "3",
        "played": "0",

        "year": "2019",
        "release_date": "06/21/2019",
        "explicit": "No",
        "languages": "English",

        "writers": ["Matt Malpass", "Lil Nas X", "Travis Barker"],
        "producers": "Travis Barker",
        "engineers": ["Eric Lagg", "Joe Grasso", "Matt Malpass"],
        "other_assistants": "",

        "key": "C major",
        "duration": "2:43",
        "bpm": "170",
        "popularity": "57",
        "energy": "53",
        "danceability": "56",
        "valence": "41",
        "acousticness": "2",
        "instrumentalness": "0",
        "liveness": "9",
        "speechiness": "3",
        "loudness": "-8",
    },

    {
        "id": "31",
        "ISRC": "USSM11903950",
        "label": "Columbia Records",
        "artist": "Lil Nas X",
        "feature": "",
        "track_title": "Kick It",
        "track_subTitle": "",
        "track_album": "7",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/seven/kickIt_song4.mp3",
        "track_coverUrl": "../material/albums/seven/seven_albumCover.jfif",

        "genres": ["Pop", "Rap", "Alternative Pop", "Alternative Rock"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "4",
        "played": "0",

        "year": "2019",
        "release_date": "06/21/2019",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["boyband", "FWDSLXSH", "Bizness Boi", "Lil Nas X"],
        "producers": ["Lil Nas X", "Bizness Boi", "FWDSLXSH", "boyband"],
        "engineers": ["Eric Lagg", "Joe Grasso", "Andy Rodriguez"],
        "other_assistants": ["johan lenox", "Danny Win", "YAS"],

        "key": "A major",
        "duration": "2:22",
        "bpm": "152",
        "popularity": "64",
        "energy": "48",
        "danceability": "74",
        "valence": "52",
        "acousticness": "14",
        "instrumentalness": "0",
        "liveness": "13",
        "speechiness": "23",
        "loudness": "-10",
    },

    {
        "id": "32",
        "ISRC": "USSM11903951",
        "label": "Columbia Records",
        "artist": ["Lil Nas X", "Cardi B"],
        "feature": "",
        "track_title": "Rodeo",
        "track_subTitle": "",
        "track_album": "7",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/seven/rodeo_song5.mp3",
        "track_coverUrl": "../material/albums/seven/seven_albumCover.jfif",

        "genres": ["Pop", "Country", "Rap", "Country Rap"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "5",
        "played": "0",

        "year": "2019",
        "release_date": "06/21/2019",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["Maxo Kream", "Pardison Fontaine", "Denzel Baptiste", "David Biral", "Klenord Raphael", "Cardi B", "Russ Chell", "Roy Lenzo", "Lil Nas X"],
        "producers": ["Russ Chell", "Roy Lenzo", "Take a Daytrip"],
        "engineers": ["Colin Leonard", "DJ Swivel", "Denzel Baptiste"],
        "other_assistants": "",

        "key": "A major",
        "duration": "2:39",
        "bpm": "140",
        "popularity": "75",
        "energy": "68",
        "danceability": "71",
        "valence": "66",
        "acousticness": "14",
        "instrumentalness": "0",
        "liveness": "47",
        "speechiness": "3",
        "loudness": "-6",
    },

    {
        "id": "33",
        "ISRC": "USSM11903952",
        "label": "Columbia Records",
        "artist": "Lil Nas X",
        "feature": "",
        "track_title": "Bring U Down",
        "track_subTitle": "",
        "track_album": "7",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/seven/bringUDown_song6.mp3",
        "track_coverUrl": "../material/albums/seven/seven_albumCover.jfif",

        "genres": ["Rock", "Cloud Rap", "Alternative Pop", "Alternative Rock", "Pop rock"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "6",
        "played": "0",

        "year": "2019",
        "release_date": "06/21/2019",
        "explicit": "No",
        "languages": "English",

        "writers": ["Zach Skelton", "Ryan Tedder", "Lil Nas X"],
        "producers": ["Zach Skelton", "Ryan Tedder"],
        "engineers": ["Eric Lagg", "Rich Rich", "Scott Desmarais", "Robin Florent", "Jeremie Inhaber"],
        "other_assistants": ["Zach Skelton", "Ryan Tedder", "Eddie Benjamin", "Eddie Fisher"],

        "key": "A minor",
        "duration": "2:12",
        "bpm": "120",
        "popularity": "64",
        "energy": "51",
        "danceability": "68",
        "valence": "48",
        "acousticness": "8",
        "instrumentalness": "0",
        "liveness": "11",
        "speechiness": "4",
        "loudness": "-7",
    },

    {
        "id": "34",
        "ISRC": "USSM11903953",
        "label": "Columbia Records",
        "artist": "Lil Nas X",
        "feature": "",
        "track_title": "C7osure",
        "track_subTitle": "(You Like)",
        "track_album": "7",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/seven/c7osure\(You\ Like\)_song7.mp3",
        "track_coverUrl": "../material/albums/seven/seven_albumCover.jfif",

        "genres": ["Alternative Indie", "R&B", "Alternative Pop", "Pop rock"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "7",
        "played": "0",

        "year": "2019",
        "release_date": "06/21/2019",
        "explicit": "No",
        "languages": "English",

        "writers": ["X-Plosive", "Abaz", "Jahaan Sweet", "Boi-1da", "Allen Ritter", "Lil Nas X"],
        "producers": ["X-Plosive", "Abaz", "Jahaan Sweet", "Allen Ritter", "Boi-1da"],
        "engineers": ["Eric Lagg", "Jaycen Joshua", "Ray Charles Brown Jr.", "Mike Seaberg", "Jacob Richards", "DJ Riggins"],
        "other_assistants": "",

        "key": "Ab minor",
        "duration": "2:29",
        "bpm": "134",
        "popularity": "66",
        "energy": "74",
        "danceability": "85",
        "valence": "56",
        "acousticness": "40",
        "instrumentalness": "0",
        "liveness": "14",
        "speechiness": "25",
        "loudness": "-6",
    },

    {
        "id": "35",
        "ISRC": "USSM11901941",
        "label": "Columbia Records",
        "artist": "Lil Nas X",
        "feature": "",
        "track_title": "Old Town Road",
        "track_subTitle": "",
        "track_album": "7",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/seven/oldTownRoad_song8.mp3",
        "track_coverUrl": "../material/albums/seven/seven_albumCover.jfif",

        "genres": ["YoungKio", "Atticus Ross", "Trent Reznor", "Lil Nas X"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "8",
        "played": "0",

        "year": "2019",
        "release_date": "06/21/2019",
        "explicit": "No",
        "languages": "English",

        "writers": ["YoungKio", "Atticus Ross", "Trent Reznor", "Lil Nas X"],
        "producers": ["Trent Reznor", "Atticus Ross", "YoungKio"],
        "engineers": "Cinco",
        "other_assistants": "",

        "key": "C# major",
        "duration": "1:53",
        "bpm": "136",
        "popularity": "79",
        "energy": "53",
        "danceability": "91",
        "valence": "51",
        "acousticness": "6",
        "instrumentalness": "0",
        "liveness": "10",
        "speechiness": "13",
        "loudness": "-6",
    },

]





const currentsBSide_EP = [

    {
        "id": "36",
        "ISRC": "AUUM71700373",
        "label": "Universal Music Australia Pty. Ltd.",
        "artist": "Tame Impala",
        "feature": "",
        "track_title": "List Of People",
        "track_subTitle": "(To Try And Forget About)",
        "track_album": "Currents",
        "track_subAlbum": "B-Sides & Remixes",

        "track_mp3Url": "../material/albums/currentsB/listOfPeople_song1.mp3",
        "track_coverUrl": "../material/albums/currentsB/currentsB_albumCover.jfif",

        "genres": ["Psychedelic Rock", "Pop"],
        "track_type": "Track",
        "album_type": ["B-Side", "Remix"],
        "track_number": "1",
        "played": "0",

        "year": "2017",
        "release_date": "11/16/2017",
        "explicit": "No",
        "languages": "English",

        "writers": "Kevin Parker",
        "producers": "Kevin Parker",
        "engineers": "",
        "other_assistants": "",

        "key": "Bb major",
        "duration": "4:40",
        "bpm": "95",
        "popularity": "56",
        "energy": "79",
        "danceability": "41",
        "valence": "20",
        "acousticness": "9",
        "instrumentalness": "0",
        "liveness": "10",
        "speechiness": "4",
        "loudness": "-6",
    },

    {
        "id": "37",
        "ISRC": "AUUM71700375",
        "label": "Universal Music Australia Pty. Ltd.",
        "artist": "Tame Impala",
        "feature": "",
        "track_title": "Powerlines",
        "track_subTitle": "",
        "track_album": "Currents",
        "track_subAlbum": "B-Sides & Remixes",

        "track_mp3Url": "../material/albums/currentsB/powerlines_song2.mp3",
        "track_coverUrl": "../material/albums/currentsB/currentsB_albumCover.jfif",

        "genres": ["Pop", "Instrumental", "Psychedelic Pop"],
        "track_type": "Track",
        "album_type": ["B-Side", "Remix"],
        "track_number": "2",
        "played": "0",

        "year": "2017",
        "release_date": "11/16/2017",
        "explicit": "No",
        "languages": "English",

        "writers": "Kevin Parker",
        "producers": "Kevin Parker",
        "engineers": "",
        "other_assistants": "",

        "key": "D major",
        "duration": "4:19",
        "bpm": "105",
        "popularity": "53",
        "energy": "89",
        "danceability": "55",
        "valence": "37",
        "acousticness": "3",
        "instrumentalness": "2",
        "liveness": "35",
        "speechiness": "4",
        "loudness": "-6",
    },

    {
        "id": "38",
        "ISRC": "AUUM71700374",
        "label": "Universal Music Australia Pty. Ltd.",
        "artist": "Tame Impala",
        "feature": "",
        "track_title": "Taxi's Here",
        "track_subTitle": "",
        "track_album": "Currents",
        "track_subAlbum": "B-Sides & Remixes",

        "track_mp3Url": "../material/albums/currentsB/taxi\'sHere_song3.mp3",
        "track_coverUrl": "../material/albums/currentsB/currentsB_albumCover.jfif",

        "genres": ["Pop", "Psychedelic Rock", "Synth pop", "Neo psychedelia", "Psychedelia"],
        "track_type": "Track",
        "album_type": ["B-Side", "Remix"],
        "track_number": "3",
        "played": "0",

        "year": "2017",
        "release_date": "11/16/2017",
        "explicit": "No",
        "languages": "English",

        "writers": "Kevin Parker",
        "producers": "Kevin Parker",
        "engineers": "",
        "other_assistants": "",

        "key": "G minor",
        "duration": "4:47",
        "bpm": "101",
        "popularity": "51",
        "energy": "57",
        "danceability": "57",
        "valence": "43",
        "acousticness": "62",
        "instrumentalness": "51",
        "liveness": "7",
        "speechiness": "3",
        "loudness": "-7",
    },

    {
        "id": "39",
        "ISRC": "AUUM71700372",
        "label": "Universal Music Australia Pty. Ltd.",
        "artist": "Tame Impala",
        "feature": "",
        "track_title": "Reality In Motion",
        "track_subTitle": "GUM Remix",
        "track_album": "Currents",
        "track_subAlbum": "B-Sides & Remixes",

        "track_mp3Url": "../material/albums/currentsB/realityInMotionGum_song4.mp3",
        "track_coverUrl": "../material/albums/currentsB/currentsB_albumCover.jfif",

        "genres": ["Pop", "Psychedelic Rock", "Synth pop", "Neo psychedelia", "Psychedelia"],
        "track_type": ["Track", "Remix"],
        "album_type": ["B-Side", "Remix"],
        "track_number": "4",
        "played": "0",

        "year": "2017",
        "release_date": "11/17/2017",
        "explicit": "No",
        "languages": "English",

        "writers": "Kevin Parker",
        "producers": "Kevin Parker",
        "engineers": "",
        "other_assistants": "",

        "key": "D major",
        "duration": "5:03",
        "bpm": "115",
        "popularity": "39",
        "energy": "66",
        "danceability": "76",
        "valence": "35",
        "acousticness": "7",
        "instrumentalness": "53",
        "liveness": "41",
        "speechiness": "10",
        "loudness": "-6",
    },

    {
        "id": "40",
        "ISRC": "AUUM71501365",
        "label": "Universal Music Australia Pty. Ltd.",
        "artist": "Tame Impala",
        "feature": "",
        "track_title": "Let It Happen",
        "track_subTitle": "Soulwax Remix",
        "track_album": "Currents",
        "track_subAlbum": "B-Sides & Remixes",

        "track_mp3Url": "../material/albums/currentsB/letItHappenSoulwax_song5.mp3",
        "track_coverUrl": "../material/albums/currentsB/currentsB_albumCover.jfif",

        "genres": ["Pop", "Psychedelic Rock", "Synth pop", "Neo psychedelia", "Psychedelia"],
        "track_type": ["Track", "Remix"],
        "album_type": ["B-Side", "Remix"],
        "track_number": "5",
        "played": "0",

        "year": "2017",
        "release_date": "11/16/2017",
        "explicit": "No",
        "languages": "English",

        "writers": "Kevin Parker",
        "producers": ["Kevin Parker", "Soulwax"],
        "engineers": "",
        "other_assistants": "",

        "key": "C# Minor",
        "duration": "9:17",
        "bpm": "125",
        "popularity": "57",
        "energy": "85",
        "danceability": "75",
        "valence": "77",
        "acousticness": "19",
        "instrumentalness": "81",
        "liveness": "11",
        "speechiness": "3",
        "loudness": "-5",
    },

]






const whereDoesTheDevilHide_EP = [

    {
        "id": "41",
        "ISRC": "USC4R2007455",
        "label": ["Easy Eye Sound", "Concord Music Group"],
        "artist": "Zella Day",
        "feature": "",
        "track_title": "People Are Strangers",
        "track_subTitle": "",
        "track_album": "Where Does The Devil Hide",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/whereDoesTheDevilHide/peopleAreStrangers_song1.mp3",
        "track_coverUrl": "../material/albums/whereDoesTheDevilHide/whereDoesTheDevilHide_albumCover.jfif",

        "genres": ["Alternative Indie", "Indie", "Alternative Pop"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "1",
        "played": "0",

        "year": "2020",
        "release_date": "08/28/2020",
        "explicit": "No",
        "languages": "English",

        "writers": ["Dan Auerbach", "Zella Day"],
        "producers": "Dan Auerbach",
        "engineers": ["Dan Auerbach", "M. Allen Parker"],
        "other_assistants": ["Sam Bacco", "Matt Combs", "Ray Jacildo", "Bobby Wood"],

        "key": "B minor",
        "duration": "2:59",
        "bpm": "68",
        "popularity": "43",
        "energy": "53",
        "danceability": "48",
        "valence": "46",
        "acousticness": "53",
        "instrumentalness": "0",
        "liveness": "12",
        "speechiness": "3",
        "loudness": "-7",
    },

    {
        "id": "42",
        "ISRC": "USC4R2007454",
        "label": ["Concord Music Group", "Easy Eye Sound"],
        "artist": "Zella Day",
        "feature": "",
        "track_title": "My Game",
        "track_subTitle": "",
        "track_album": "Where Does The Devil Hide",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/whereDoesTheDevilHide/myGame_song2.mp3",
        "track_coverUrl": "../material/albums/whereDoesTheDevilHide/whereDoesTheDevilHide_albumCover.jfif",

        "genres": ["Alternative Indie", "Indie Pop", "Indie", "Alternative Pop", "Funk", "Soft Rock"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "2",
        "played": "0",

        "year": "2020",
        "release_date": "08/28/2020",
        "explicit": "No",
        "languages": "English",

        "writers": ["Bobby Wood", "Dan Auerbach", "Zella Day"],
        "producers": "Dan Auerbach",
        "engineers": ["Dan Auerbach", "M. Allen Parker"],
        "other_assistants": ["Bobby Wood", "Dan Auerbach", "Sam Bacco", "Matt Combs", "Dave Roe", "Ray Jacildo"],

        "key": "D minor",
        "duration": "3:30",
        "bpm": "124",
        "popularity": "42",
        "energy": "78",
        "danceability": "70",
        "valence": "88",
        "acousticness": "24",
        "instrumentalness": "0",
        "liveness": "9",
        "speechiness": "3",
        "loudness": "-7",
    },

    {
        "id": "43",
        "ISRC": "USC4R2007456",
        "label": ["Easy Eye Sound", "Concord Music Group"],
        "artist": "Zella Day",
        "feature": "",
        "track_title": "Purple Haze",
        "track_subTitle": "",
        "track_album": "Where Does The Devil Hide",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/whereDoesTheDevilHide/purpleHaze_song3.mp3",
        "track_coverUrl": "../material/albums/whereDoesTheDevilHide/whereDoesTheDevilHide_albumCover.jfif",

        "genres": ["Pop", "Alternative", "Indie"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "3",
        "played": "0",

        "year": "2020",
        "release_date": "07/10/2020",
        "explicit": "No",
        "languages": "English",

        "writers": ["Dan Nigro", "Dan Auerbach", "Zella Day"],
        "producers": "Dan Auerbach",
        "engineers": ["Dan Auerbach", "M. Allen Parker"],
        "other_assistants": "",

        "key": "B minor",
        "duration": "3:19",
        "bpm": "125",
        "popularity": "46",
        "energy": "67",
        "danceability": "65",
        "valence": "59",
        "acousticness": "4",
        "instrumentalness": "1",
        "liveness": "14",
        "speechiness": "4",
        "loudness": "-8",
    },

    {
        "id": "44",
        "ISRC": "USC4R2007457",
        "label": ["Easy Eye Sound", "Concord Music Group"],
        "artist": "Zella Day",
        "feature": "",
        "track_title": "Only A Dream",
        "track_subTitle": "",
        "track_album": "Where Does The Devil Hide",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/whereDoesTheDevilHide/onlyADream_song4.mp3",
        "track_coverUrl": "../material/albums/whereDoesTheDevilHide/whereDoesTheDevilHide_albumCover.jfif",

        "genres": ["Pop", "Alternative", "Indie"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "4",
        "played": "0",

        "year": "2020",
        "release_date": "08/28/2020",
        "explicit": "No",
        "languages": "English",

        "writers": ["Dan Nigro", "Dan Auerbach", "Zella Day"],
        "producers": "Dan Auerbach",
        "engineers": "",
        "other_assistants": ["Dan Auerbach", "Ray Jacildo", "Bobby Wood", "Dave Roe", "Matt Combs"],

        "key": "C major",
        "duration": "3:30",
        "bpm": "120",
        "popularity": "41",
        "energy": "50",
        "danceability": "51",
        "valence": "36",
        "acousticness": "67",
        "instrumentalness": "0",
        "liveness": "22",
        "speechiness": "3",
        "loudness": "-7",
    },

    {
        "id": "45",
        "ISRC": "USC4R2007458",
        "label": ["Easy Eye Sound", "Concord Music Group"],
        "artist": "Zella Day",
        "feature": "",
        "track_title": "Benny My Dear",
        "track_subTitle": "",
        "track_album": "Where Does The Devil Hide",
        "track_subAlbum": "",

        "track_mp3Url": "../material/albums/whereDoesTheDevilHide/bennyMyDear_song5.mp3",
        "track_coverUrl": "../material/albums/whereDoesTheDevilHide/whereDoesTheDevilHide_albumCover.jfif",

        "genres": ["Pop", "Alternative", "Indie"],
        "track_type": "Track",
        "album_type": "EP",
        "track_number": "5",
        "played": "0",

        "year": "2020",
        "release_date": "08/28/2020",
        "explicit": "No",
        "languages": "English",

        "writers": ["Dan Auerbach", "Zella Day"],
        "producers": "Dan Auerbach",
        "engineers": ["Dan Auerbach", "M. Allen Parker"],
        "other_assistants": ["Bobby Wood", "Sam Bacco", "Dan Auerbach", "Dave Roe", "Ray Jacildo"],

        "key": "C major",
        "duration": "3:19",
        "bpm": "110",
        "popularity": "30",
        "energy": "69",
        "danceability": "55",
        "valence": "77",
        "acousticness": "35",
        "instrumentalness": "0",
        "liveness": "16",
        "speechiness": "3",
        "loudness": "-7",
    },

]

const albumLibrary = [myDearMelancholy_EP, seven_EP, currentsBSide_EP, whereDoesTheDevilHide_EP];


const musicLibrary = [
    {
        "id": "1",
        "ISRC": "QM42K1946534",
        "label": "Portwave",
        "artist": "Portwave",
        "feature": "",
        "track_title": "Shadow Lady",
        "track_subTitle": "",
        "track_album": "",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/shadowLady_song1.mp3",
        "track_coverUrl": "../material/song_artCovers/shadowLady_song1.jfif",

        "genres": "Electronic",
        "track_type": "Single",
        "album_type": "",
        "track_number": "",
        "played": "0",

        "year": "2014",
        "release_date": "01/05/2014",
        "explicit": "No",
        "languages": "English",

        "writers": "",
        "producers": "",
        "engineers": "",
        "other_assistants": "",

        "key": "Bb minor",
        "duration": "5:02",
        "bpm": "104",
        "popularity": "67",
        "energy": "87",
        "danceability": "56",
        "valence": "56",
        "acousticness": "0",
        "instrumentalness": "85",
        "liveness": "18",
        "speechiness": "7",
        "loudness": "-3",
    },

    {
        "id": "2",
        "ISRC": "QZF8N1986577",
        "label": "Revolution Records",
        "artist": "Mareux",
        "feature": "",
        "track_title": "The Perfect Girl",
        "track_subTitle": "",
        "track_album": "",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/thePerfectGirl_song2.mp3",
        "track_coverUrl": "../material/song_artCovers/thePerfectGirl_song2.jfif",

        "genres": ["Darkwave", "Synthwave", "Electronic"],
        "track_type": "Single",
        "album_type": "",
        "track_number": "",
        "played": "0",

        "year": "2019",
        "release_date": "10/13/2019",
        "explicit": "No",
        "languages": "English",

        "writers": "Aryan Ashtiani",
        "producers": "",
        "engineers": "",
        "other_assistants": "",

        "key": "Ab minor",
        "duration": "3:14",
        "bpm": "129",
        "popularity": "79",
        "energy": "89",
        "danceability": "49",
        "valence": "26",
        "acousticness": "0",
        "instrumentalness": "82",
        "liveness": "10",
        "speechiness": "9",
        "loudness": "-6",
    },
    {
        "id": "3",
        "ISRC": "USY251660155",
        "label": "Negative Gain Productions",
        "artist": ["Mr.Kitty", "XO LOVER"],
        "feature": "",
        "track_title": "after dark",
        "track_subTitle": "(slowed)",
        "track_album": "",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/afterDark_song3.mp3",
        "track_coverUrl": "../material/song_artCovers/afterDark_song3.jfif",

        "genres": ["Synthpop", "Synthwave", "Electronic"],
        "track_type": ["Single", "Remix"],
        "album_type": "",
        "track_number": "",
        "played": "0",

        "year": "2021",
        "release_date": "07/04/2021",
        "explicit": "No",
        "languages": "English",

        "writers": "",
        "producers": "",
        "engineers": "",
        "other_assistants": "",

        "key": "128",
        "duration": "4:36",
        "bpm": "128",
        "popularity": "81",
        "energy": "54",
        "danceability": "54",
        "valence": "4",
        "acousticness": "7",
        "instrumentalness": "27",
        "liveness": "8",
        "speechiness": "3",
        "loudness": "-10.4",
    },

    {
        "id": "4",
        "ISRC": "DEZ651364854",
        "label": "Dais Records",
        "artist": "Tempers",
        "feature": "",
        "track_title": "Undoing",
        "track_subTitle": "",
        "track_album": "Services",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/undoing_song4.mp3",
        "track_coverUrl": "../material/song_artCovers/undoing_song4.jfif",

        "genres": ["Synthpop", "Rock", "Electronic", "Dark Indie"],
        "track_type": "Track",
        "album_type": "Studio",
        "track_number": "2",
        "played": "0",

        "year": "2015",
        "release_date": "10/23/2015",
        "explicit": "No",
        "languages": "English",

        "writers": "",
        "producers": "",
        "engineers": "",
        "other_assistants": "",

        "key": "Bb major",
        "duration": "3:51",
        "bpm": "155",
        "popularity": "25",
        "energy": "89",
        "danceability": "35",
        "valence": "18",
        "acousticness": "5",
        "instrumentalness": "74",
        "liveness": "22",
        "speechiness": "4",
        "loudness": "-4",
    },

    {
        "id": "5",
        "ISRC": "USUM71111638",
        "label": ["Roc Nation", "RocAFella", "IDJ"],
        "artist": ["JAY-Z", "Kanye West"],
        "feature": "",
        "track_title": "Primetime",
        "track_subTitle": "",
        "track_album": "Watch The Throne",
        "track_subAlbum": "Deluxe",

        "track_mp3Url": "../material/songs_mp3/primetime_song5.mp3",
        "track_coverUrl": "../material/song_artCovers/primetime_song5.jfif",

        "genres": ["Hip-hop", "Rap"],
        "track_type": "Track",
        "album_type": "Deluxe",
        "track_number": "15",
        "played": "0",

        "year": "2011",
        "release_date": "10/08/2011",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["Maureen Reid", "Larry Smith", "No I.D.", "Russell Simmons", "JAY-Z", "Kanye West"],
        "producers": "",
        "engineers": ["Noah Goldstein", "MIKE DEAN"],
        "other_assistants": ["Ken Lewis", "Brent Kolatalo", "Dylan Wissing"],

        "key": "B minor",
        "duration": "3:19",
        "bpm": "85",
        "popularity": "54",
        "energy": "92",
        "danceability": "66",
        "valence": "47",
        "acousticness": "17",
        "instrumentalness": "0",
        "liveness": "31",
        "speechiness": "21",
        "loudness": "-4",
    },

    {
        "id": "6",
        "ISRC": "USUM71111678",
        "label": ["Roc Nation", "RocAFella", "IDJ"],
        "artist": ["JAY-Z", "Kanye West"],
        "feature": "Mr.Hudson",
        "track_title": "Why I Love You",
        "track_subTitle": "",
        "track_album": "Watch The Throne",
        "track_subAlbum": "Deluxe",

        "track_mp3Url": "../material/songs_mp3/whyILoveYou_song6.mp3",
        "track_coverUrl": "../material/song_artCovers/whyILoveYou_song6.jfif",

        "genres": ["Hip-hop", "Rap"],
        "track_type": "Track",
        "album_type": "Deluxe",
        "track_number": "12",
        "played": "0",

        "year": "2011",
        "release_date": "10/08/2011",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["Boom Bass", "Philippe Zdar", "Mary Sawyer", "Tony Camillo", "MIKE DEAN", "S. Joseph", "JAY-Z", "Kanye West"],
        "producers": "",
        "engineers": ["Noah Goldstein", "MIKE DEAN", "Anthony Kilhoffer"],
        "other_assistants": ["Mat Arnold", "MIKE DEAN", "Anthony Kilhoffer", "Chris “Hitchcock” Chorney"],

        "key": "F Major",
        "duration": "3:21",
        "bpm": "123",
        "popularity": "60",
        "energy": "81",
        "danceability": "48",
        "valence": "37",
        "acousticness": "3",
        "instrumentalness": "0",
        "liveness": "27",
        "speechiness": "4",
        "loudness": "-4",
    },

    {
        "id": "7",
        "ISRC": "USUM71307523",
        "label": ["G.O.O.D. Music", "Def Jam Recordings"],
        "artist": "Kanye West",
        "feature": "",
        "track_title": "Bound 2",
        "track_subTitle": "",
        "track_album": "Yeezus",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/bound2_song7.mp3",
        "track_coverUrl": "../material/song_artCovers/bound2_song7.jfif",

        "genres": ["Hip-hop", "Rap"],
        "track_type": "Track",
        "album_type": "Studio",
        "track_number": "10",
        "played": "0",

        "year": "2013",
        "release_date": "06/18/2013",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["John Legend", "No I.D.", "Lester Allen McKenzie", "Noah Goldstein", "MIKE DEAN", "The World Famous Tony Williams", "Ronnie Self", "Robert Dukes", "Bob Massey", "Norman Whiteside", "Sakiya Sandifer", "Malik Yusef", "CyHi The Prynce", "Elon Rutberg", "Che Pope", "Charlie Wilson", "Kanye West"],
        "producers": "Rick Rubin",
        "engineers": ["Vlado Meller", "Manny Marroquin", "Anthony Kilhoffer", "Noah Goldstein", "Delbert Bowers", "Chris Galland"],
        "other_assistants": ["Charlie Wilson", "MIKE DEAN"],

        "key": "C# major",
        "duration": "3:49",
        "bpm": "149",
        "popularity": "82",
        "energy": "67",
        "danceability": "37",
        "valence": "31",
        "acousticness": "14",
        "instrumentalness": "0",
        "liveness": "11",
        "speechiness": "5",
        "loudness": "-3",
    },

    {
        "id": "8",
        "ISRC": "USUM71703084",
        "label": ["Interscope Records", "Top Dawg Entertainment", "Aftermath Entertainment"],
        "artist": "Kendrick Lamar",
        "feature": "",
        "track_title": "PRIDE.",
        "track_subTitle": "",
        "track_album": "DAMN.",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/pride._song8.mp3",
        "track_coverUrl": "../material/song_artCovers/pride._song8.jfif",

        "genres": ["Hip-hop", "R&B", "Rap", "Pop"],
        "track_type": "Track",
        "album_type": "Studio",
        "track_number": "7",
        "played": "0",

        "year": "2017",
        "release_date": "04/14/2017",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["Anna Wise", "Steve Lacy", "Kendrick Lamar"],
        "producers": "Bēkon",
        "engineers": ["Mike Bozzi", "Mixed by Ali", "Tyler Page", "Ya Boy N.O.I.S."],
        "other_assistants": ["Bēkon", "Anna Wise", "Steve Lacy"],

        "key": "E minor",
        "duration": "4:35",
        "bpm": "139",
        "popularity": "77",
        "energy": "54",
        "danceability": "67",
        "valence": "37",
        "acousticness": "8",
        "instrumentalness": "0",
        "liveness": "15",
        "speechiness": "6",
        "loudness": "-7",
    },

    {
        "id": "9",
        "ISRC": "FRZID0900480",
        "label": "Parlophone (France)",
        "artist": "David Guetta",
        "feature": "Kid Cudi",
        "track_title": "Memories",
        "track_subTitle": "",
        "track_album": "One Love",
        "track_subAlbum": "Deluxe",

        "track_mp3Url": "../material/songs_mp3/memories_song9.mp3",
        "track_coverUrl": "../material/song_artCovers/memories_song9.jfif",

        "genres": ["Pop", "EDM", "Rap", "Electronic", "House", "Dance"],
        "track_type": "Track",
        "album_type": "Deluxe",
        "track_number": "3",
        "played": "0",

        "year": "2009",
        "release_date": "08/21/2009",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["Kid Cudi", "David Guetta", "Frédéric Riesterer"],
        "producers": ["David Guetta", "Frédéric Riesterer"],
        "engineers": "",
        "other_assistants": "",

        "key": "Ab major",
        "duration": "3:30",
        "bpm": "130",
        "popularity": "69",
        "energy": "87",
        "danceability": "56",
        "valence": "50",
        "acousticness": "0",
        "instrumentalness": "0",
        "liveness": "25",
        "speechiness": "34",
        "loudness": "-6",
    },

    {
        "id": "10",
        "ISRC": "DKEW50600101",
        "label": " Ultra Records",
        "artist": ["Enur", "Natasja"],
        "feature": "",
        "track_title": "Calabria 2007",
        "track_subTitle": "Radio Edit",
        "track_album": "",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/calabria2007_song10.mp3",
        "track_coverUrl": "../material/song_artCovers/calabria2007_song10.jfif",

        "genres": "",
        "track_type": "Radio Edit",
        "album_type": "",
        "track_number": "",
        "played": "0",

        "year": "2007",
        "release_date": "07/10/2007",
        "explicit": "No",
        "languages": "English",

        "writers": "",
        "producers": "",
        "engineers": "",
        "other_assistants": "",

        "key": "G major",
        "duration": "3:53",
        "bpm": "126",
        "popularity": "41",
        "energy": "55",
        "danceability": "89",
        "valence": "44",
        "acousticness": "1",
        "instrumentalness": "8",
        "liveness": "6",
        "speechiness": "19",
        "loudness": "-8",
    },

    {
        "id": "11",
        "ISRC": "USJI10600477",
        "label": ["Reservoir Media", "Jive Records"],
        "artist": "Justin Timberlake",
        "feature": "T.I.",
        "track_title": "My Love",
        "track_subTitle": "",
        "track_album": "FutureSex/LoveSounds",
        "track_subAlbum": "Deluxe Version",

        "track_mp3Url": "../material/songs_mp3/myLove_song11.mp3",
        "track_coverUrl": "../material/song_artCovers/myLove_song11.jfif",

        "genres": ["Pop", "R&B", "Rap"],
        "track_type": "Track",
        "album_type": "Deluxe",
        "track_number": "4",
        "played": "0",

        "year": "2006",
        "release_date": "09/13/2006",
        "explicit": "No",
        "languages": "English",

        "writers": ["T.I.", "Timbaland", "Justin Timberlake", "Danja"],
        "producers": ["Danja", "Justin Timberlake", "Timbaland"],
        "engineers": ["Herb Powers", "Timbaland", "Jimmy Douglass", "Ethan Willoughby"],
        "other_assistants": "",

        "key": "B minor",
        "duration": "4:36",
        "bpm": "120",
        "popularity": "74",
        "energy": "68",
        "danceability": "77",
        "valence": "81",
        "acousticness": "28",
        "instrumentalness": "0",
        "liveness": "68",
        "speechiness": "22",
        "loudness": "-6",
    },

    {
        "id": "12",
        "ISRC": "GB28K1200052",
        "label": "Parlophone (France)",
        "artist": "David Guetta",
        "feature": ["Ne-Yo", "Akon"],
        "track_title": "Play Hard",
        "track_subTitle": "",
        "track_album": "Nothing But the Beat 2.0",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/playHard_song12.mp3",
        "track_coverUrl": "../material/song_artCovers/playHard_song12.jfif",

        "genres": ["Pop", "Dance", "House", "EDM"],
        "track_type": "Track",
        "album_type": "Studio",
        "track_number": "6",
        "played": "0",

        "year": "2011",
        "release_date": "10/24/2011",
        "explicit": "No",
        "languages": "English",

        "writers": ["Frédéric Riesterer, Giorgio Tuinfort, David Guetta, Akon & Ne-Yo"],
        "producers": ["Frédéric Riesterer", "Giorgio Tuinfort", "David Guetta"],
        "engineers": "",
        "other_assistants": "",

        "key": "Ab minor",
        "duration": "3:21",
        "bpm": "130",
        "popularity": "62",
        "energy": "92",
        "danceability": "69",
        "valence": "80",
        "acousticness": "17",
        "instrumentalness": "0",
        "liveness": "33",
        "speechiness": "5",
        "loudness": "-2",
    },

    {
        "id": "13",
        "ISRC": "NLA320119533",
        "label": ["EMI Group Limited", "Roadrunner Records"],
        "artist": "Nickelback",
        "feature": "",
        "track_title": "How You Remind Me",
        "track_subTitle": "",
        "track_album": "Silver Side Up",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/howYouRemindMe_song13.mp3",
        "track_coverUrl": "../material/song_artCovers/howYouRemindMe_song13.jfif",

        "genres": ["Rock", "Alternative Metal", "Alternative Rock", "Hard Rock", "Postgrunge"],
        "track_type": "Track",
        "album_type": "Studio",
        "track_number": "2",
        "played": "0",

        "year": "2001",
        "release_date": "09/11/2001",
        "explicit": "No",
        "languages": "English",

        "writers": ["Ryan Vikedal, Ryan Peake, Mike Kroeger & Chad Kroeger"],
        "producers": "Rick Parashar",
        "engineers": "",
        "other_assistants": "",

        "key": "Bb major",
        "duration": "3:44",
        "bpm": "172",
        "popularity": "81",
        "energy": "76",
        "danceability": "45",
        "valence": "54",
        "acousticness": "0",
        "instrumentalness": "0",
        "liveness": "10",
        "speechiness": "3",
        "loudness": "-5",
    },

    {
        "id": "14",
        "ISRC": "USJAY0300080",
        "label": "Interscope Records",
        "artist": "Maroon 5",
        "feature": "",
        "track_title": "This Love",
        "track_subTitle": "",
        "track_album": "Songs About Jane",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/thisLove_song14.mp3",
        "track_coverUrl": "../material/song_artCovers/thisLove_song14.jfif",

        "genres": ["Rock", "Pop", "Alternative Rock"],
        "track_type": "Track",
        "album_type": "Studio",
        "track_number": "2",
        "played": "0",

        "year": "2002",
        "release_date": "06/25/2002",
        "explicit": "No",
        "languages": "English",

        "writers": ["James Valentine", "Michael Madden", "Ryan Dusick", "Jesse Carmichael", "Adam Levine"],
        "producers": ["Mark Endert", "Matt Vallace"],
        "engineers": ["Leon Zervos", "Mark Endert", "Mike Landolt", "Danny Wright", "Posie Muliadi"],
        "other_assistants": "",

        "key": "F minor",
        "duration": "3:26",
        "bpm": "95",
        "popularity": "70",
        "energy": "86",
        "danceability": "71",
        "valence": "81",
        "acousticness": "5",
        "instrumentalness": "0",
        "liveness": "9",
        "speechiness": "4",
        "loudness": "-5",
    },

    {
        "id": "15",
        "ISRC": "DEL211300741",
        "label": ["Ignition Records", "Republic Records", "Opaque", "Lichtdicht"],
        "artist": "Milky Chance",
        "feature": "",
        "track_title": "Stolen Dance",
        "track_subTitle": "",
        "track_album": "Sadnecessary",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/stolenDance_song15.mp3",
        "track_coverUrl": "../material/song_artCovers/stolenDance_song15.jfif",

        "genres": ["Indie Pop", "Pop", "Psychedelic Folk", "Folktronica"],
        "track_type": "Track",
        "album_type": "Studio",
        "track_number": "11",
        "played": "0",

        "year": "2014",
        "release_date": "06/20/14",
        "explicit": "No",
        "languages": "English",

        "writers": "Clemens Rehbein",
        "producers": "",
        "engineers": "",
        "other_assistants": "",

        "key": "B major",
        "duration": "5:14",
        "bpm": "114",
        "popularity": "75",
        "energy": "58",
        "danceability": "89",
        "valence": "73",
        "acousticness": "43",
        "instrumentalness": "0",
        "liveness": "8",
        "speechiness": "4",
        "loudness": "-9",
    },

    {
        "id": "16",
        "ISRC": "USUM71203514",
        "label": "Interscope Records",
        "artist": "Maroon 5",
        "feature": "",
        "track_title": "One More Night",
        "track_subTitle": "",
        "track_album": "Overexposed",
        "track_subAlbum": "Deluxe",

        "track_mp3Url": "../material/songs_mp3/oneMoreNight_song16.mp3",
        "track_coverUrl": "../material/song_artCovers/oneMoreNight_song16.jfif",

        "genres": ["Pop", "Dance Pop"],
        "track_type": "Track",
        "album_type": "Deluxe",
        "track_number": "1",
        "played": "0",

        "year": "2012",
        "release_date": "06/19/2012",
        "explicit": "No",
        "languages": "English",

        "writers": ["Max Martin", "Savan Kotecha", "Shellback", "Adam Levine"],
        "producers": ["Shellback", "Max Martin"],
        "engineers": ["Max Martin", "Noah Passovoy", "John Hanes", "Șerban Ghenea", "Phil Seaford", "Eric Eylands"],
        "other_assistants": ["Shellback", "Max Martin", "Matt Flynn", "James Valentine", "Adam Levine", "Shellback", "PJ Morton"],

        "key": "F minor",
        "duration": "3:39",
        "bpm": "93",
        "popularity": "70",
        "energy": "82",
        "danceability": "72",
        "valence": "61",
        "acousticness": "4",
        "instrumentalness": "0",
        "liveness": "8",
        "speechiness": "3",
        "loudness": "-3",
    },

    {
        "id": "17",
        "ISRC": "USRC11803252",
        "label": ["A$AP Rocky Recordings, Polo Grounds Music, Sony Music Entertainment, A$AP Worldwide & RCA Records"],
        "artist": "A$AP Rocky",
        "feature": "",
        "track_title": "Sundress",
        "track_subTitle": "",
        "track_album": "",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/sundress_song17.mp3",
        "track_coverUrl": "../material/song_artCovers/sundress_song17.jfif",

        "genres": ["Psychedelic Pop", "Pop Rap", "Rap", "Indie Pop"],
        "track_type": "Single",
        "album_type": "",
        "track_number": "",
        "played": "0",

        "year": "2018",
        "release_date": "11/20/2018",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["Kevin Parker", "Hector Delgado", "Danger Mouse", "Syk Sense", "A$AP Rocky"],
        "producers": ["Syk Sense", "Danger Mouse", "A$AP Rocky", "Hector Delgado"],
        "engineers": ["Tatsuya Sato", "Andy Jackson 88", "Beatriz Artola", "Hector Delgado"],
        "other_assistants": "",

        "key": "F# major",
        "duration": "2:38",
        "bpm": "125",
        "popularity": "79",
        "energy": "71",
        "danceability": "72",
        "valence": "74",
        "acousticness": "18",
        "instrumentalness": "0",
        "liveness": "14",
        "speechiness": "6",
        "loudness": "-6",
    },

    {
        "id": "18",
        "ISRC": "AUUM71500303",
        "label": ["Interscope Records", "Modular Recordings"],
        "artist": "Tame Impala",
        "feature": "",
        "track_title": "The Less I Know the Better",
        "track_subTitle": "",
        "track_album": "Currents",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/theLessIKnowTheBetter_song18.mp3",
        "track_coverUrl": "../material/song_artCovers/theLessIKnowTheBetter_song18.jfif",

        "genres": ["Psychedelic Rock", "Psychedelic Pop", "Rock", "Alternative", "Indie", "Psychedelic", "Synthpop"],
        "track_type": "Track",
        "album_type": "Studio",
        "track_number": "7",
        "played": "0",

        "year": "2015",
        "release_date": "07/17/2015",
        "explicit": "Yes",
        "languages": "English",

        "writers": "Kevin Parker",
        "producers": "Kevin Parker",
        "engineers": ["Greg Calbi", "Kevin Parker", "Rob Grant"],
        "other_assistants": "",

        "key": "E major",
        "duration": "3:36",
        "bpm": "117",
        "popularity": "86",
        "energy": "74",
        "danceability": "64",
        "valence": "79",
        "acousticness": "1",
        "instrumentalness": "1",
        "liveness": "17",
        "speechiness": "3",
        "loudness": "-4",
    },

    {
        "id": "19",
        "ISRC": "USAT21907692",
        "label": ["Epic Records", "Atlantic Records", "Cactus Jack Records", "WeRunItEnt", "Artist Partner Group"],
        "artist": "Don Toliver",
        "feature": ["Quavo", "Offset"],
        "track_title": "Had Enough",
        "track_subTitle": "",
        "track_album": "Heaven Or Hell",
        "track_subAlbum": "",

        "track_mp3Url": "../material/songs_mp3/hadEnough_song19.mp3",
        "track_coverUrl": "../material/song_artCovers/hadEnough_song19.jfif",

        "genres": ["Hip-hop", "Rap", "Cloud Rap"],
        "track_type": "Track",
        "album_type": "Studio",
        "track_number": "9",
        "played": "0",

        "year": "2020",
        "release_date": "03/13/2020",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["Cool", "Homer Steinweiss", "Dre", "Beyoncé", "Michael Herard", "James Fauntleroy", "JAY-Z", "Thomas Brenneck", "WondaGurl", "Leon Michels", "MIKE DEAN", "TM88", "Don Toliver", "Quavo & Offset"],
        "producers": ["CA$HPASSION", "Leon Michels", "MIKE DEAN", "TM88"],
        "engineers": ["MIKE DEAN", "JRich ENT", "Colton Eatmon", "Lemon Blue", "Kai Lasker", "Shawn Morenberg"],
        "other_assistants": "",

        "key": "D major",
        "duration": "2:37",
        "bpm": "148",
        "popularity": "67",
        "energy": "79",
        "danceability": "75",
        "valence": "67",
        "acousticness": "26",
        "instrumentalness": "0",
        "liveness": "13",
        "speechiness": "11",
        "loudness": "-5",
    },

    {
        "id": "20",
        "ISRC": "USUM72023838",
        "label": ["Republic Records", "Wicked Awesome Records"],
        "artist": "Kid Cudi",
        "feature": "",
        "track_title": "Tequila Shots",
        "track_subTitle": "",
        "track_album": "Man on the Moon III:",
        "track_subAlbum": "The Chosen",

        "track_mp3Url": "../material/songs_mp3/tequilaShots_song20.mp3",
        "track_coverUrl": "../material/song_artCovers/tequilaShots_song20.jfif",

        "genres": ["Psychedelic Rap", "Hip-hop", "Rap", "Trap"],
        "track_type": "Track",
        "album_type": ["Studio", "Series"],
        "track_number": "2",
        "played": "0",

        "year": "2020",
        "release_date": "12/11/2020",
        "explicit": "Yes",
        "languages": "English",

        "writers": ["Denzel Baptiste", "David Biral", "Dot Da Genius", "Kid Cudi"],
        "producers": ["Kid Cudi", "Dot Da Genius", "Take a Daytrip"],
        "engineers": ["Joe LaPorta", "William J. Sullivan", "Manny Marroquin"],
        "other_assistants": "",

        "key": "F minor",
        "duration": "3:13",
        "bpm": "90",
        "popularity": "79",
        "energy": "56",
        "danceability": "71",
        "valence": "22",
        "acousticness": "8",
        "instrumentalness": "0",
        "liveness": "53",
        "speechiness": "5",
        "loudness": "-7",
    },
]